site_name: Ayaka - 文字游戏开发辅助插件
repo_url: https://github.com/bridgeL/nonebot-plugin-ayaka
repo_name: nonebot-plugin-ayaka

theme:
  name: material
  palette:
    primary: brown
  features:
    - content.code.annotate
    - navigation.tabs
  custom_dir: overrides
nav:
  - 主页:
    - 介绍: index.md
    - 安装: intro/install.md
    - 快速开始: intro/quick_start.md
    - 测试: intro/test.md
    - 内置插件: intro/master.md
    - 其他用语: intro/term.md
  - 更多示例:
    - 介绍: more/index.md
    - 多级菜单: more/menu.md
    - 多次输入: more/mult_input.md
    - 整点报时: more/clock.md
    - 分割参数: more/split.md
    - 浏览器截图: more/baidu.md
  - 开发衍生插件:
    - 前置内容: develop/index.md
    - 速览: develop/api.md
    - 注册回调: develop/on.md
    - 数据读写: develop/storage.md
    - 浏览器截图: develop/browser.md
    - 属性: develop/property.md
    - 方法: develop/function.md
  - 小游戏合集:
    - 介绍: games/index.md
    - 安装: games/install.md
    - 谁是卧底: games/who-is-suspect.md
    - 更多帮助: games/help.md
  - 更新记录:
    - 未来计划: change-log/next.md
    - v4: change-log/v4.md
    - v3: change-log/v3.md
    - v2: change-log/v2.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: 本页索引
      permalink: true
extra:
  version:
    provider: mike
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'
extra_javascript:
  - javascripts/version-mike.js
