# Project information
site_name: Ayaka - 为群聊插件开发提供状态机支持
site_url: https://bridgel.github.io/ayaka_doc/

# Repository
repo_name: nonebot-plugin-ayaka
repo_url: https://github.com/bridgeL/nonebot-plugin-ayaka/

# Copyright
copyright: Copyright &copy; 2022 - 2022 bridgeL

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: brown
    accent: blue
  features:
  - content.code.copy
  - content.tabs.link
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.tracking
  - navigation.top
  - navigation.footer
  - toc.integrate
  - search.highlight
  - search.suggest
  hide:
    - toc
nav:
- 主页: index.md
- 快速开始: quick_start.md
- 开发衍生插件:
  - 概念介绍: develop/intro.md
  - 星际旅行: develop/travel.md
- 小游戏合集:
  - 介绍: games/game.md
  - 安装与配置: games/install.md
  - 更多帮助: games/help.md
  - 更新日志: games/change-log.md
- 更新日志:
  - 未来计划: change-log/next.md
  - box: change-log/box.md
  - v5: change-log/v5.md
  - v4: change-log/v4.md
  - v3: change-log/v3.md
  - v2: change-log/v2.md
- API: api/index.html

markdown_extensions:
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true 
- toc:
    title: 本页索引
    permalink: true


plugins:
- search:
    lang:
    - en
    - ja
    separator: '[\s\-\.]+'
      
extra:
  version:
    provider: mike

extra_javascript:
- js/version.js
- js/demo.js
extra_css:
- css/code.css
- css/tab-right.css
- css/big-font.css
- css/demo.css
