# Project information
site_name: Ayaka - 文字游戏开发辅助插件
site_url: https://bridgel.github.io/ayaka_doc/

# Repository
repo_name: nonebot-plugin-ayaka
repo_url: https://github.com/bridgeL/nonebot-plugin-ayaka/

# Copyright
copyright: Copyright &copy; 2022 - 2022 bridgeL

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: brown
  features:
  - content.code.annotate
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.tracking
  - navigation.top
  - toc.integrate
  - search.highlight
  - search.suggest
  hide:
    - toc
nav:
- 主页: 
  - 介绍: index.md
  - 安装: intro/install.md
  - 常见问题: intro/qa.md
  - 快速开始: intro/quick_start.md
  - 测试: intro/test.md
  - 内置插件: intro/master.md
  - 其他用语: intro/term.md
- 更多示例: 
  - 更多示例: more/index.md
  - 多级菜单: more/menu.md
  - 多次输入: more/mult_input.md
  - 整点报时: more/clock.md
  - 分割参数: more/split.md
  - 浏览器截图: more/baidu.md
- 开发衍生插件:
  - 前置内容: develop/index.md
  - 速览: develop/api.md
  - 开启应用: develop/open.md
  - 注册回调: develop/on.md
  - 浏览器截图: develop/browser.md
  - 缓存: develop/cache.md
  - 持久化: develop/storage.md
  - 解析: develop/parser.md
  - 配置: develop/config.md
- 小游戏合集:
  - 介绍: games/index.md
  - 安装: games/install.md
  - 谁是卧底: games/who-is-suspect.md
  - 更多帮助: games/help.md
- 更新日志:
  - 未来计划: change-log/next.md
  - v5: change-log/v5.md
  - v4: change-log/v4.md
  - v3: change-log/v3.md
  - v2: change-log/v2.md
- API: https://bridgel.github.io/nonebot-plugin-ayaka/

markdown_extensions:
- pymdownx.highlight:
    linenums_style: pymdownx-inline
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- toc:
    title: 本页索引
    permalink: true

plugins:
- search:
    lang:
    - en
    - ja
    separator: '[\s\-\.]+'
      
extra:
  version:
    provider: mike

extra_javascript:
- js/version.js
extra_css:
- css/code.css
- css/tab-right.css
- css/big-font.css
