site_name: Ayaka - 文字游戏开发辅助插件
repo_url: https://github.com/bridgeL/nonebot-plugin-ayaka
repo_name: nonebot-plugin-ayaka

theme:
  name: material
  palette:
    primary: brown
  features:
    - content.code.annotate
    - navigation.tabs
nav:
  - 主页:
      - 介绍: index.md
      - 安装: intro/install.md
      - 快速开始: intro/why.md
      - 测试: intro/test.md
      - 有状态与无状态: intro/state.md
      - ayaka_master: intro/master.md
  - 更多示例:
      - 介绍: why/index.md
      - 多级菜单: why/menu.md
  - 开发:
      - 前置内容: plugin/index.md
      - 速览: plugin/api.md
      - 属性: plugin/property.md
      - 注册回调: plugin/on.md
      - 数据读写: plugin/storage.md
      - 浏览器截图: plugin/browser.md
  - 小游戏合集:
      - 介绍: games/index.md
      - 安装: games/install.md
      - 谁是卧底: games/who-is-suspect.md
      - 更多帮助: games/help.md
  - 更新记录:
      - 未来计划: change-log/next.md
      - v4: change-log/v4.md
      - v3: change-log/v3.md
      - v2: change-log/v2.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: 本页索引
      permalink: true
# extra_javascript:
#   - fake-qq/main.js
# extra_css:
#   - fake-qq/style.css
