# Project information
site_name: Ayaka - 文字游戏开发辅助插件
site_url: https://bridgel.github.io/ayaka_doc/

# Repository
repo_name: nonebot-plugin-ayaka
repo_url: https://github.com/bridgeL/nonebot-plugin-ayaka/

# Copyright
copyright: Copyright &copy; 2022 - 2022 bridgeL

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: brown
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.suggest

nav:
  - 主页:
      - 介绍: index.md
      - 安装: intro/install.md
      - 开发:
          - 快速开始: intro/quick_start.md
          - 测试: intro/test.md
          - 内置插件: intro/master.md
          - 其他用语: intro/term.md
  - 更多示例:
      - 介绍: more/index.md
      - 状态机:
          - 多级菜单: more/menu.md
          - 多次输入: more/mult_input.md
      - 其他功能:
          - 整点报时: more/clock.md
          - 分割参数: more/split.md
          - 浏览器截图: more/baidu.md
  - 开发衍生插件:
      - 前置内容: develop/index.md
      - 速览: develop/api.md
      - 开启应用: develop/open.md
      - 注册回调: develop/on.md
      - 数据读写: develop/storage.md
      - 浏览器截图: develop/browser.md
      - 解析: develop/parser.md
  - API:
    - ayaka: api/ayaka/ayaka.md
    - ayaka_master: api/ayaka/ayaka_master.md
    - cache: api/ayaka/cache.md
    - config: api/ayaka/config.md
    - constant: api/ayaka/constant.md
    - deal: api/ayaka/deal.md
    - group: api/ayaka/group.md
    - json_ctrl: api/ayaka/json_ctrl.md
    - "on": api/ayaka/on.md
    - parser: api/ayaka/parser.md
    - playwright: api/ayaka/playwright.md
    - storage: api/ayaka/storage.md
    - driver:
      - __init__: api/ayaka/driver/__init__.md
      - ayakabot_driver: api/ayaka/driver/ayakabot_driver.md
      - ayakabot:
        - bot: api/ayaka/driver/ayakabot/bot.md
        - driver: api/ayaka/driver/ayakabot/driver.md
        - event: api/ayaka/driver/ayakabot/event.md
        - message: api/ayaka/driver/ayakabot/message.md
        - model: api/ayaka/driver/ayakabot/model.md
        - result: api/ayaka/driver/ayakabot/result.md
        - template: api/ayaka/driver/ayakabot/template.md
        - utils: api/ayaka/driver/ayakabot/utils.md
        - websocket: api/ayaka/driver/ayakabot/websocket.md
  - 小游戏合集:
      - 介绍: games/index.md
      - 安装: games/install.md
      - 游戏帮助:
          - 谁是卧底: games/who-is-suspect.md
          - 更多帮助: games/help.md
  - 更新日志:
      - 未来计划: change-log/next.md
      - v4: change-log/v4.md
      - v3: change-log/v3.md
      - v2: change-log/v2.md

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: 本页索引
      permalink: true

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+'
      
extra:
  version:
    provider: mike

extra_javascript:
  - javascript/version-mike.js
extra_css:
  - css/code.css
