[tool.poetry]
name = "ayaka-doc"
version = "0.1.0"
description = ""
authors = ["Su <wxlxy316@163.com>"]
readme = "README.md"
packages = [{include = "ayaka_doc"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
